### ISSUE TITLE
有没有办法加前缀

### ISSUE THREAD

**Issue by kaiqigong** [chenboxiang/grunt-qiniu-deploy#4]
我想把静态文件部署到qiniu bucket下的某个路径。现在只能本地把文件目录整一下然后上传。

**Comment by chenboxiang** [comment]
指定路径，有个选项，你可以看下 options.keyGen，默认是直接返回的file相对cwd的路径，你可以自己加上前缀

**Comment by kaiqigong** [comment]
@chenboxiang 
cool 感谢！
