### ISSUE TITLE
文件名相同时，不是根据对文件hash以后的key值，来判断文件是否存在？

### ISSUE THREAD

**Issue by aisuhua** [chenboxiang/grunt-qiniu-deploy#6]
我试过先上传几个文件，然后**对这几个文件内容进行修改后**，再次上传，还是提示： The key [xxxx] exists, so ignore it.。

我这边经过多次测试都是这样，但我看到最近一个更新 _“应当检查key是否存在，而非file"_，相信也是解决这个问题的，但是我这边测试不行。

我看到七牛官方给出了相同文件更新问题的解决方法，如果能够实现，那就太好了。你可以看看：[如何避免用户上传相同的文件](http://kb.qiniu.com/53tubk96)

我的环境：

```
node  v0.10.36
npm   1.4.28
grunt-qiniu-deploy 0.1.4
```

谢谢！

**Comment by chenboxiang** [comment]
这个问题是这样：同名文件上传后，缓存不会即时更新，这样就造成了用户实际访问的文件不是最新的，但开发者那边其实已经发布了。  我建议你不要传同名的文件，而是先对你的静态资源做下处理，在名称上加上内容的摘要（如MD5值），这样保证只要文件内容变了就会更新。

**Comment by chenboxiang** [comment]
如果你依然还是想上传，那你可以fork下我的代码，从130行开始，调整下逻辑就行。

**Comment by aisuhua** [comment]
恩恩，原来是这样子，非常感谢了！
